### ISSUE TITLE
Attribution to Marlin project

### ISSUE THREAD

**Issue by AlexDaniel** [bread-maker/firmware#2]
It was openly admitted that parts of [temperature.c](https://github.com/bread-maker/bread-maker-firmware/blob/master/temperature.c) were taken from another project (was it [Marlin](https://github.com/MarlinFirmware/Marlin/blob/1.1.x/Marlin/temperature.cpp)?), but nowhere in the file it says so. I think a simple link to the original source should be good enough. Both projects are under GPL so there's no issue, but attribution is still required.

**Comment by ClusterM** [comment]
You are right, i'll add link to Marlin.
